/**
 * Tortoise Merchant API
 * Tortoise API for merchant to integrate with their existing systems 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@tortoise.pro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Customer {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("firstName")
  private String firstName = null;
  @SerializedName("lastName")
  private String lastName = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("mobile")
  private String mobile = null;
  @SerializedName("countryCode")
  private String countryCode = null;
  @SerializedName("age")
  private Integer age = null;
  public enum GenderEnum {
     male,  female,  other, 
  };
  @SerializedName("gender")
  private GenderEnum gender = null;
  public enum KycStatusEnum {
     pending,  inProcess,  verified,  failed, 
  };
  @SerializedName("kycStatus")
  private KycStatusEnum kycStatus = null;

  /**
   * Unique identifier for the customer
   **/
  @ApiModelProperty(value = "Unique identifier for the customer")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * Customer's first name. For example, Surya Harsha
   **/
  @ApiModelProperty(value = "Customer's first name. For example, Surya Harsha")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   * Customer's last name. For example, Singh
   **/
  @ApiModelProperty(value = "Customer's last name. For example, Singh")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMobile() {
    return mobile;
  }
  public void setMobile(String mobile) {
    this.mobile = mobile;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountryCode() {
    return countryCode;
  }
  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getAge() {
    return age;
  }
  public void setAge(Integer age) {
    this.age = age;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public GenderEnum getGender() {
    return gender;
  }
  public void setGender(GenderEnum gender) {
    this.gender = gender;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public KycStatusEnum getKycStatus() {
    return kycStatus;
  }
  public void setKycStatus(KycStatusEnum kycStatus) {
    this.kycStatus = kycStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Customer customer = (Customer) o;
    return (this.id == null ? customer.id == null : this.id.equals(customer.id)) &&
        (this.firstName == null ? customer.firstName == null : this.firstName.equals(customer.firstName)) &&
        (this.lastName == null ? customer.lastName == null : this.lastName.equals(customer.lastName)) &&
        (this.email == null ? customer.email == null : this.email.equals(customer.email)) &&
        (this.mobile == null ? customer.mobile == null : this.mobile.equals(customer.mobile)) &&
        (this.countryCode == null ? customer.countryCode == null : this.countryCode.equals(customer.countryCode)) &&
        (this.age == null ? customer.age == null : this.age.equals(customer.age)) &&
        (this.gender == null ? customer.gender == null : this.gender.equals(customer.gender)) &&
        (this.kycStatus == null ? customer.kycStatus == null : this.kycStatus.equals(customer.kycStatus));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.firstName == null ? 0: this.firstName.hashCode());
    result = 31 * result + (this.lastName == null ? 0: this.lastName.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.mobile == null ? 0: this.mobile.hashCode());
    result = 31 * result + (this.countryCode == null ? 0: this.countryCode.hashCode());
    result = 31 * result + (this.age == null ? 0: this.age.hashCode());
    result = 31 * result + (this.gender == null ? 0: this.gender.hashCode());
    result = 31 * result + (this.kycStatus == null ? 0: this.kycStatus.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Customer {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  mobile: ").append(mobile).append("\n");
    sb.append("  countryCode: ").append(countryCode).append("\n");
    sb.append("  age: ").append(age).append("\n");
    sb.append("  gender: ").append(gender).append("\n");
    sb.append("  kycStatus: ").append(kycStatus).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
