/**
 * Tortoise Merchant API
 * Tortoise API for merchant to integrate with their existing systems 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@tortoise.pro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.Plan;
import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Payment {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("plan")
  private Plan plan = null;
  @SerializedName("instalmentId")
  private Integer instalmentId = null;
  public enum ModeEnum {
     debit,  credit,  upi,  netbanking,  cash, 
  };
  @SerializedName("mode")
  private ModeEnum mode = null;
  @SerializedName("amount")
  private Integer amount = null;
  @SerializedName("createdOn")
  private Date createdOn = null;
  public enum StatusEnum {
     successful,  failed,  refunded,  refundInitiated,  processing, 
  };
  @SerializedName("status")
  private StatusEnum status = null;

  /**
   * Unique identifier for the payment
   **/
  @ApiModelProperty(value = "Unique identifier for the payment")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Plan getPlan() {
    return plan;
  }
  public void setPlan(Plan plan) {
    this.plan = plan;
  }

  /**
   * Instalment serial number for which the payment has been made
   **/
  @ApiModelProperty(value = "Instalment serial number for which the payment has been made")
  public Integer getInstalmentId() {
    return instalmentId;
  }
  public void setInstalmentId(Integer instalmentId) {
    this.instalmentId = instalmentId;
  }

  /**
   * Mode of payment
   **/
  @ApiModelProperty(value = "Mode of payment")
  public ModeEnum getMode() {
    return mode;
  }
  public void setMode(ModeEnum mode) {
    this.mode = mode;
  }

  /**
   * Amount paid on the payment
   **/
  @ApiModelProperty(value = "Amount paid on the payment")
  public Integer getAmount() {
    return amount;
  }
  public void setAmount(Integer amount) {
    this.amount = amount;
  }

  /**
   * Timestamp at which the payment has been made
   **/
  @ApiModelProperty(value = "Timestamp at which the payment has been made")
  public Date getCreatedOn() {
    return createdOn;
  }
  public void setCreatedOn(Date createdOn) {
    this.createdOn = createdOn;
  }

  /**
   * Status of the payment
   **/
  @ApiModelProperty(value = "Status of the payment")
  public StatusEnum getStatus() {
    return status;
  }
  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Payment payment = (Payment) o;
    return (this.id == null ? payment.id == null : this.id.equals(payment.id)) &&
        (this.plan == null ? payment.plan == null : this.plan.equals(payment.plan)) &&
        (this.instalmentId == null ? payment.instalmentId == null : this.instalmentId.equals(payment.instalmentId)) &&
        (this.mode == null ? payment.mode == null : this.mode.equals(payment.mode)) &&
        (this.amount == null ? payment.amount == null : this.amount.equals(payment.amount)) &&
        (this.createdOn == null ? payment.createdOn == null : this.createdOn.equals(payment.createdOn)) &&
        (this.status == null ? payment.status == null : this.status.equals(payment.status));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.plan == null ? 0: this.plan.hashCode());
    result = 31 * result + (this.instalmentId == null ? 0: this.instalmentId.hashCode());
    result = 31 * result + (this.mode == null ? 0: this.mode.hashCode());
    result = 31 * result + (this.amount == null ? 0: this.amount.hashCode());
    result = 31 * result + (this.createdOn == null ? 0: this.createdOn.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Payment {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  plan: ").append(plan).append("\n");
    sb.append("  instalmentId: ").append(instalmentId).append("\n");
    sb.append("  mode: ").append(mode).append("\n");
    sb.append("  amount: ").append(amount).append("\n");
    sb.append("  createdOn: ").append(createdOn).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
