/**
 * Tortoise Merchant API
 * Tortoise API for merchant to integrate with their existing systems 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@tortoise.pro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Product {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("category")
  private String category = null;
  public enum StatusEnum {
     active,  disabled,  reviewPending,  reviewRejected, 
  };
  @SerializedName("status")
  private StatusEnum status = null;
  @SerializedName("price")
  private Integer price = null;
  @SerializedName("createdOn")
  private Date createdOn = null;
  @SerializedName("updatedOn")
  private Date updatedOn = null;

  /**
   * Unique Identifier for the product
   **/
  @ApiModelProperty(value = "Unique Identifier for the product")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * Name of the product
   **/
  @ApiModelProperty(value = "Name of the product")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Name of the category that product belongs to
   **/
  @ApiModelProperty(value = "Name of the category that product belongs to")
  public String getCategory() {
    return category;
  }
  public void setCategory(String category) {
    this.category = category;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }
  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPrice() {
    return price;
  }
  public void setPrice(Integer price) {
    this.price = price;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getCreatedOn() {
    return createdOn;
  }
  public void setCreatedOn(Date createdOn) {
    this.createdOn = createdOn;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getUpdatedOn() {
    return updatedOn;
  }
  public void setUpdatedOn(Date updatedOn) {
    this.updatedOn = updatedOn;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Product product = (Product) o;
    return (this.id == null ? product.id == null : this.id.equals(product.id)) &&
        (this.name == null ? product.name == null : this.name.equals(product.name)) &&
        (this.category == null ? product.category == null : this.category.equals(product.category)) &&
        (this.status == null ? product.status == null : this.status.equals(product.status)) &&
        (this.price == null ? product.price == null : this.price.equals(product.price)) &&
        (this.createdOn == null ? product.createdOn == null : this.createdOn.equals(product.createdOn)) &&
        (this.updatedOn == null ? product.updatedOn == null : this.updatedOn.equals(product.updatedOn));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.category == null ? 0: this.category.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.price == null ? 0: this.price.hashCode());
    result = 31 * result + (this.createdOn == null ? 0: this.createdOn.hashCode());
    result = 31 * result + (this.updatedOn == null ? 0: this.updatedOn.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Product {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  category: ").append(category).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  createdOn: ").append(createdOn).append("\n");
    sb.append("  updatedOn: ").append(updatedOn).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
