/**
 * Tortoise Merchant API
 * Tortoise API for merchant to integrate with their existing systems 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@tortoise.pro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.SchemeRedemptionOption;
import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Scheme {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("createdOn")
  private Date createdOn = null;
  public enum StatusEnum {
     active,  disabled,  reviewPending,  reviewRejected, 
  };
  @SerializedName("status")
  private StatusEnum status = null;
  @SerializedName("redemptionOption")
  private SchemeRedemptionOption redemptionOption = null;
  @SerializedName("durationInMonths")
  private Integer durationInMonths = null;

  /**
   * Unique identifier for the scheme
   **/
  @ApiModelProperty(value = "Unique identifier for the scheme")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * Name of the scheme
   **/
  @ApiModelProperty(value = "Name of the scheme")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Timestamp at which the scheme is created
   **/
  @ApiModelProperty(value = "Timestamp at which the scheme is created")
  public Date getCreatedOn() {
    return createdOn;
  }
  public void setCreatedOn(Date createdOn) {
    this.createdOn = createdOn;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }
  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public SchemeRedemptionOption getRedemptionOption() {
    return redemptionOption;
  }
  public void setRedemptionOption(SchemeRedemptionOption redemptionOption) {
    this.redemptionOption = redemptionOption;
  }

  /**
   * Duration of the scheme in months, in other words, number of instalments to be paid by the customer
   **/
  @ApiModelProperty(value = "Duration of the scheme in months, in other words, number of instalments to be paid by the customer")
  public Integer getDurationInMonths() {
    return durationInMonths;
  }
  public void setDurationInMonths(Integer durationInMonths) {
    this.durationInMonths = durationInMonths;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Scheme scheme = (Scheme) o;
    return (this.id == null ? scheme.id == null : this.id.equals(scheme.id)) &&
        (this.name == null ? scheme.name == null : this.name.equals(scheme.name)) &&
        (this.createdOn == null ? scheme.createdOn == null : this.createdOn.equals(scheme.createdOn)) &&
        (this.status == null ? scheme.status == null : this.status.equals(scheme.status)) &&
        (this.redemptionOption == null ? scheme.redemptionOption == null : this.redemptionOption.equals(scheme.redemptionOption)) &&
        (this.durationInMonths == null ? scheme.durationInMonths == null : this.durationInMonths.equals(scheme.durationInMonths));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.createdOn == null ? 0: this.createdOn.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.redemptionOption == null ? 0: this.redemptionOption.hashCode());
    result = 31 * result + (this.durationInMonths == null ? 0: this.durationInMonths.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Scheme {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  createdOn: ").append(createdOn).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  redemptionOption: ").append(redemptionOption).append("\n");
    sb.append("  durationInMonths: ").append(durationInMonths).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
